require 'test_helper'

class PdfMergingServiceDataColumnTest < ActiveSupport::TestCase
  test 'should group photos correctly with new data structure' do
    # Mock photo attachments with filenames that would be generated by the new data structure
    photo1 = mock_photo_attachment('inspection_123_section_1__field_name_abc123.jpg')
    photo2 = mock_photo_attachment('inspection_123_section_2__another_field_def456.jpg')
    photo3 = mock_photo_attachment('inspection_123_section_1__second_field_ghi789.jpg')

    images = [photo1, photo2, photo3]

    grouped = PdfMergingService.group_and_process_photos(images)

    # Should group by section
    assert_includes grouped.keys, 'Section 1'
    assert_includes grouped.keys, 'Section 2'

    # Section 1 should have 2 photos
    assert_equal 2, grouped['Section 1'].length

    # Section 2 should have 1 photo
    assert_equal 1, grouped['Section 2'].length

    # Verify photo data structure
    section_1_photos = grouped['Section 1']
    assert(section_1_photos.all? { |p| p.key?(:image) && p.key?(:clean_name) })

    # Verify clean names are processed correctly
    clean_names = section_1_photos.map { |p| p[:clean_name] }
    assert_includes clean_names, 'Field name'
    assert_includes clean_names, 'Second field'
  end

  test 'should handle photos with new attachment ID format' do
    # Test with photo filenames that include the new attachment ID format
    # These would be generated by FormFill#generate_unique_photo_attachment_id
    photo1 = mock_photo_attachment('inspection_456_fire_extinguisher__location_row_1_xyz123.jpg')
    photo2 = mock_photo_attachment('inspection_456_sprinkler_system__valve_check_abc789.jpg')

    images = [photo1, photo2]

    grouped = PdfMergingService.group_and_process_photos(images)

    # Should group correctly
    assert_includes grouped.keys, 'Fire extinguisher'
    assert_includes grouped.keys, 'Sprinkler system'

    # Verify clean names
    fire_extinguisher_photo = grouped['Fire extinguisher'].first
    assert_equal 'Location row 1', fire_extinguisher_photo[:clean_name]

    sprinkler_photo = grouped['Sprinkler system'].first
    assert_equal 'Valve check', sprinkler_photo[:clean_name]
  end

  test 'should handle uncategorized photos gracefully' do
    # Test with photos that don't match the expected pattern
    photo1 = mock_photo_attachment('random_photo.jpg')
    photo2 = mock_photo_attachment('another_image.png')
    photo3 = mock_photo_attachment('inspection_123_valid_section__field_name_abc123.jpg')

    images = [photo1, photo2, photo3]

    grouped = PdfMergingService.group_and_process_photos(images)

    # Should have both categorized and uncategorized sections
    assert_includes grouped.keys, 'Valid section'
    assert_includes grouped.keys, 'Uncategorized Photos'

    # Uncategorized should have 2 photos
    assert_equal 2, grouped['Uncategorized Photos'].length

    # Valid section should have 1 photo
    assert_equal 1, grouped['Valid section'].length
  end

  test 'should handle empty or invalid images array' do
    # Test with empty array
    grouped = PdfMergingService.group_and_process_photos([])
    assert_equal({}, grouped)

    # Test with nil
    grouped = PdfMergingService.group_and_process_photos(nil)
    assert_equal({}, grouped)

    # Test with non-array object that doesn't respond to each
    grouped = PdfMergingService.group_and_process_photos('not an array')
    assert_equal({}, grouped)
  end

  test 'should handle photos with invalid or missing filenames' do
    # Test with photos that have nil or invalid filenames
    valid_photo = mock_photo_attachment('inspection_123_section_1__field_name_abc123.jpg')
    invalid_photo1 = mock_photo_attachment(nil)
    invalid_photo2 = Object.new # Photo without filename method

    images = [valid_photo, invalid_photo1, invalid_photo2]

    # Should not raise an error
    assert_nothing_raised do
      grouped = PdfMergingService.group_and_process_photos(images)

      # Should only process the valid photo
      assert_equal 1, grouped.keys.length
      assert_includes grouped.keys, 'Section 1'
      assert_equal 1, grouped['Section 1'].length
    end
  end

  test 'should maintain existing photo organization in PDFs' do
    # This test ensures that the photo organization remains the same
    # with the new data structure as it was with the old structure

    # Create photos with the same naming pattern as before
    photo1 = mock_photo_attachment('inspection_789_main_system__pressure_gauge_1_def123.jpg')
    photo2 = mock_photo_attachment('inspection_789_main_system__flow_meter_2_ghi456.jpg')
    photo3 = mock_photo_attachment('inspection_789_backup_system__valve_status_1_jkl789.jpg')

    images = [photo1, photo2, photo3]

    grouped = PdfMergingService.group_and_process_photos(images)

    # Should maintain the same grouping logic
    assert_equal 2, grouped.keys.length
    assert_includes grouped.keys, 'Main system'
    assert_includes grouped.keys, 'Backup system'

    # Main system should have 2 photos
    main_system_photos = grouped['Main system']
    assert_equal 2, main_system_photos.length

    # Verify the photos are organized correctly
    clean_names = main_system_photos.map { |p| p[:clean_name] }
    assert_includes clean_names, 'Pressure gauge 1'
    assert_includes clean_names, 'Flow meter 2'

    # Backup system should have 1 photo
    backup_system_photos = grouped['Backup system']
    assert_equal 1, backup_system_photos.length
    assert_equal 'Valve status 1', backup_system_photos.first[:clean_name]
  end

  test 'should work with mock PDF object for add_images_to_pdf' do
    # Test the full add_images_to_pdf method with mocked dependencies
    pdf_object = mock_pdf_object

    photo1 = mock_photo_attachment('inspection_123_test_section__test_field_abc123.jpg')
    photo2 = mock_photo_attachment('inspection_123_test_section__another_field_def456.jpg')

    # Wrap photos in hashes as expected by add_images_to_pdf
    images = [
      { photo: photo1, section_name: 'test_section', label_name: 'test_field' },
      { photo: photo2, section_name: 'test_section', label_name: 'another_field' }
    ]

    # Mock the image download to return fake image data
    photo1.stubs(:download).returns('fake image data 1')
    photo2.stubs(:download).returns('fake image data 2')

    # Mock Prawn document creation
    mock_prawn_doc = mock('prawn_document')
    mock_prawn_doc.stubs(:render).returns('rendered pdf data')

    Prawn::Document.stubs(:new).returns(mock_prawn_doc)

    # Mock CombinePDF parsing
    mock_parsed_pdf = mock('parsed_pdf')
    CombinePDF.stubs(:parse).with('rendered pdf data').returns(mock_parsed_pdf)

    # Expect the PDF object to receive the parsed PDF
    pdf_object.expects(:<<).with(mock_parsed_pdf)

    # Call the method
    result = PdfMergingService.add_images_to_pdf(pdf_object, images, title: 'Test Photos')

    # Should return the original PDF object
    assert_equal pdf_object, result
  end

  test 'should return original PDF object when no images provided' do
    pdf_object = mock_pdf_object

    # Test with empty images
    result = PdfMergingService.add_images_to_pdf(pdf_object, [], title: 'Test Photos')
    assert_equal pdf_object, result

    # Test with nil images
    result = PdfMergingService.add_images_to_pdf(pdf_object, nil, title: 'Test Photos')
    assert_equal pdf_object, result
  end

  private

  def mock_photo_attachment(filename)
    photo = mock('photo_attachment')

    if filename
      filename_mock = mock('filename')
      filename_mock.stubs(:base).returns(filename.split('.').first)
      photo.stubs(:filename).returns(filename_mock)
    else
      photo.stubs(:filename).returns(nil)
    end

    photo
  end

  def mock_pdf_object
    pdf_object = mock('pdf_object')
    pdf_object.stubs(:<<)
    pdf_object
  end
end
